agent_categories_with_subcategories = {
    "Technology": [
        "Artificial Intelligence",
        "Software Development",
        "Cybersecurity",
        "Cloud Computing",
        "Mobile Apps",
        "Web Development",
        "Data Science",
        "Blockchain",
        "Internet of Things",
        "Hardware & Electronics"
    ],
    "Health": [
        "Mental Health",
        "Nutrition & Diet",
        "Fitness & Exercise",
        "Medical Research",
        "Preventive Care",
        "Women's Health",
        "Men's Health",
        "Pediatric Health",
        "Senior Care",
        "Alternative Medicine"
    ],
    "Finance": [
        "Personal Finance",
        "Investment Strategies",
        "Cryptocurrency",
        "Banking Services",
        "Insurance",
        "Real Estate",
        "Retirement Planning",
        "Tax Planning",
        "Business Finance",
        "Economic Analysis"
    ],
    "Education": [
        "Online Learning",
        "K-12 Education",
        "Higher Education",
        "Vocational Training",
        "Language Learning",
        "STEM Education",
        "Educational Technology",
        "Professional Development",
        "Special Education",
        "Educational Research"
    ],
    "Entertainment": [
        "Movies & TV",
        "Streaming Services",
        "Celebrity News",
        "Books & Literature",
        "Podcasts",
        "Live Events",
        "Comedy",
        "Theatre",
        "Animation",
        "Digital Content"
    ],
    "Travel": [
        "Destination Guides",
        "Budget Travel",
        "Luxury Travel",
        "Adventure Travel",
        "Business Travel",
        "Family Travel",
        "Solo Travel",
        "Cultural Tourism",
        "Eco Tourism",
        "Travel Planning"
    ],
    "Sports": [
        "Professional Sports",
        "Olympic Sports",
        "Fantasy Sports",
        "Extreme Sports",
        "Youth Sports",
        "Sports Analytics",
        "Fitness Sports",
        "Motor Sports",
        "Water Sports",
        "Winter Sports"
    ],
    "Food": [
        "Cooking Recipes",
        "Restaurant Reviews",
        "Food Trends",
        "Healthy Eating",
        "International Cuisine",
        "Food Safety",
        "Meal Planning",
        "Food Photography",
        "Wine & Beverages",
        "Food Industry"
    ],
    "Lifestyle": [
        "Home & Garden",
        "Personal Development",
        "Relationships",
        "Parenting",
        "Hobbies & Crafts",
        "Productivity",
        "Minimalism",
        "Wellness",
        "Time Management",
        "Self-Care"
    ],
    "Fashion": [
        "Fashion Trends",
        "Sustainable Fashion",
        "Designer Brands",
        "Street Style",
        "Beauty & Cosmetics",
        "Accessories",
        "Fashion Technology",
        "Vintage Fashion",
        "Plus Size Fashion",
        "Men's Fashion"
    ],
    "Art": [
        "Contemporary Art",
        "Digital Art",
        "Traditional Painting",
        "Sculpture",
        "Photography",
        "Graphic Design",
        "Art History",
        "Street Art",
        "Installation Art",
        "Art Collecting"
    ],
    "Music": [
        "Pop Music",
        "Rock & Metal",
        "Hip Hop & Rap",
        "Electronic Music",
        "Classical Music",
        "Jazz & Blues",
        "Country Music",
        "World Music",
        "Music Production",
        "Live Concerts"
    ],
    "Gaming": [
        "Video Game Reviews",
        "Mobile Gaming",
        "PC Gaming",
        "Console Gaming",
        "Esports",
        "Game Development",
        "Virtual Reality",
        "Retro Gaming",
        "Gaming Hardware",
        "Gaming Culture"
    ],
    "Environment": [
        "Climate Change",
        "Renewable Energy",
        "Conservation",
        "Sustainability",
        "Pollution Control",
        "Wildlife Protection",
        "Green Technology",
        "Environmental Policy",
        "Recycling & Waste",
        "Eco-Friendly Living"
    ],
    "Politics": [
        "Government Policy",
        "Elections & Voting",
        "International Relations",
        "Political Analysis",
        "Civil Rights",
        "Local Politics",
        "Political History",
        "Public Policy",
        "Political Economy",
        "Democracy & Governance"
    ],
    "Science": [
        "Space Exploration",
        "Medical Research",
        "Physics & Chemistry",
        "Biology & Genetics",
        "Earth Sciences",
        "Scientific Innovation",
        "Research Methods",
        "Science Education",
        "Environmental Science",
        "Technology & Science"
    ],
    "History": [
        "Ancient History",
        "Modern History",
        "Military History",
        "Cultural History",
        "Historical Biography",
        "Archaeological Discoveries",
        "Historical Documents",
        "Social History",
        "Historical Analysis",
        "Local History"
    ],
    "Culture": [
        "Cultural Traditions",
        "Language & Literature",
        "Religious Studies",
        "Social Anthropology",
        "Cultural Events",
        "Folk Culture",
        "Pop Culture",
        "Cultural Exchange",
        "Cultural Preservation",
        "Multicultural Studies"
    ],
    "Automotive": [
        "Car Reviews",
        "Electric Vehicles",
        "Auto Technology",
        "Classic Cars",
        "Motorcycle Culture",
        "Auto Racing",
        "Car Maintenance",
        "Automotive Industry",
        "Car Buying Guides",
        "Transportation Innovation"
    ]
}